name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC
  workflow_dispatch:

jobs:
  update-readme-1:
    name: Update README Run 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update README
        run: |
          DAY=$(date +"%-d")
          case "$DAY" in
            1|21|31) SUFFIX="st" ;;
            2|22)    SUFFIX="nd" ;;
            3|23)    SUFFIX="rd" ;;
            *)       SUFFIX="th" ;;
          esac

          DATE=$(date +"%A, ${DAY}${SUFFIX} %B %Y")
          echo "<!-- update run 1 on ${DATE} -->" >> README.md
          sed -i "s|Last updated on .* using magic ✨|Last updated on ${DATE} using magic ✨|g" README.md

      - name: Commit and Push
        run: |
          git config --global user.name 'AnshAjayMishra'
          git config --global user.email 'ajayanshmishra10@gmail.com'
          git add README.md
          git commit -m "Update README (run 1)" || echo "No changes"
          git push || echo "Push failed (likely due to conflict)"

  update-readme-2:
    name: Update README Run 2
    needs: update-readme-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update README
        run: |
          DATE=$(date +"%A, %-d %B %Y")
          echo "<!-- update run 2 on ${DATE} -->" >> README.md
      - name: Commit and Push
        run: |
          git config --global user.name 'AnshAjayMishra'
          git config --global user.email 'ajayanshmishra10@gmail.com'
          git add README.md
          git commit -m "Update README (run 2)" || echo "No changes"
          git push || echo "Push failed (likely due to conflict)"

  update-readme-3:
    name: Update README Run 3
    needs: update-readme-2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update README
        run: |
          DATE=$(date +"%A, %-d %B %Y")
          echo "<!-- update run 3 on ${DATE} -->" >> README.md
      - name: Commit and Push
        run: |
          git config --global user.name 'AnshAjayMishra'
          git config --global user.email 'ajayanshmishra10@gmail.com'
          git add README.md
          git commit -m "Update README (run 3)" || echo "No changes"
          git push || echo "Push failed (likely due to conflict)"

  update-readme-4:
    name: Update README Run 4
    needs: update-readme-3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update README
        run: |
          DATE=$(date +"%A, %-d %B %Y")
          echo "<!-- update run 4 on ${DATE} -->" >> README.md
      - name: Commit and Push
        run: |
          git config --global user.name 'AnshAjayMishra'
          git config --global user.email 'ajayanshmishra10@gmail.com'
          git add README.md
          git commit -m "Update README (run 4)" || echo "No changes"
          git push || echo "Push failed (likely due to conflict)"
