name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        count: [1, 2, 3, 4]  # This will run the job 4 times

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print current directory
        run: pwd

      - name: Check README before update
        run: cat README.md

      - name: Update README
        run: |
          DAY=$(date +"%-d")
          case "$DAY" in
            1|21|31) SUFFIX="st" ;;
            2|22)    SUFFIX="nd" ;;
            3|23)    SUFFIX="rd" ;;
            *)       SUFFIX="th" ;;
          esac

          DATE=$(date +"%A, ${DAY}${SUFFIX} %B %Y")
          RUN_ID=${{ matrix.count }}

          echo "Updating README with date: ${DATE}, run #${RUN_ID}"

          # Update line
          sed -i "s|Last updated on .* using magic ✨|Last updated on ${DATE} using magic ✨|g" README.md

          # Add different lines for each run to force a unique commit
          echo "<!-- update run ${RUN_ID} on ${DATE} -->" >> README.md

      - name: Commit and Push changes
        run: |
          git config --global user.name 'AnshAjayMishra'
          git config --global user.email 'ajayanshmishra10@gmail.com'

          git add README.md

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update README (run ${{ matrix.count }})"
            git push
          fi
