name: Update Date in README

on:
  schedule:
    - cron: '30 6 * * *'  # Runs daily at 12:00 PM IST
  workflow_dispatch:       # Optional manual trigger

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set current date in IST
        id: date
        run: |
          echo "date=Last updated on $(TZ='Asia/Kolkata' date '+%A, %dth %B %Y') using magic ✨" >> "$GITHUB_ENV"

      - name: Update README.md with new date
        run: |
          sed -i '/^Last updated on/c\'"$date" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "anshajaymishra"
          git config --global user.email "ajayanshmishra@gmail.com"
          git add README.md
          git commit -m "📅 Daily README update" || echo "No changes to commit"
          git push
