name: Update README

on:
  schedule:
    - cron: '30 18 * * *'  # 12:00 AM IST (6:30 PM UTC)
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    strategy:
      matrix:
        run: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'AnshAjayMishra'
          git config --global user.email 'ajayanshmishra10@gmail.com'
          git config pull.rebase true

      - name: Pull latest changes
        run: git pull

      - name: Update README
        run: |
          # Get IST time (UTC+5:30)
          IST_DATE=$(TZ="Asia/Kolkata" date +"%A, %-d")
          DAY=$(TZ="Asia/Kolkata" date +"%-d")
          
          # Add ordinal suffix
          case "$DAY" in
            1|21|31) SUFFIX="st" ;;
            2|22)    SUFFIX="nd" ;;
            3|23)    SUFFIX="rd" ;;
            *)       SUFFIX="th" ;;
          esac

          FULL_DATE=$(TZ="Asia/Kolkata" date +"%A, ${DAY}${SUFFIX} %B %Y")
          
          # Update README with run number
          sed -i "s|Last updated on .* using magic ✨|Last updated on ${FULL_DATE} using magic ✨ (Run ${{ matrix.run }}/4)|" README.md

      - name: Commit and push changes
        run: |
          git add README.md
          git commit -m "📅 Daily update (Run ${{ matrix.run }}/4 at $(TZ="Asia/Kolkata" date +'%H:%M IST'))"
          git push
