name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  workflow_dispatch: # manual trigger too

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print current directory
        run: pwd

      - name: Check README before update
        run: cat README.md

      - name: Update README
        run: |
          DAY=$(date +"%-d")
          case "$DAY" in
            1|21|31) SUFFIX="st" ;;
            2|22)    SUFFIX="nd" ;;
            3|23)    SUFFIX="rd" ;;
            *)       SUFFIX="th" ;;
          esac
          
          DATE=$(date +"%A, ${DAY}${SUFFIX} %B %Y")

          echo "Updating README with date: ${DATE}"

          # Update the README file
          sed -i "s|Last updated on .* using magic ✨|Last updated on ${DATE} using magic ✨|g" README.md

      - name: Check changes in README
        run: git diff README.md

      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md

          # Commit only if there are changes
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update README last updated date"
            git push
          fi
